common:
  number_of_intermediate_imgs: 10
  reactant_file: "resources/reactant.con"
  product_file: "resources/product.con"
eon:
  config: "resources/config.ini"
  num_steps: 28
pet_mad:
  version: "v1.1.0"
plotting:
  plot_structures: "crit_points"
  facecolor: "floralwhite"
  title: "NEB Energy Profile"
