# -*- mode:snakemake; -*-
from snakemake.utils import min_version

min_version("6.0")


# Path to config file containing general variables, relative to the workflow folder
configfile: "config/general_config.yml"


module ira_align:
    snakefile:
        "rules/ira_align.smk"
    config:
        config


module ase_idpp:
    snakefile:
        "rules/ase_idpp.smk"
    config:
        config


module get_petmad:
    snakefile:
        "rules/get_petmad.smk"
    config:
        config


module run_eon:
    snakefile:
        "rules/run_eon.smk"
    config:
        config


module plotting:
    snakefile:
        "rules/plotting.smk"
    config:
        config


use rule * from ira_align as __ira_align_*


use rule * from ase_idpp as __ase_idpp_*


use rule * from get_petmad


use rule * from run_eon


use rule plot_neb_path from plotting


rule minimize_endpoints:
    input:
        expand(
            f"{config['paths']['endpoints']}/{{endpoint}}_minimized.con",
            endpoint=["reactant", "product"],
        ),


rule all:
    input:
        rules.plot_neb_path.output,
    default_target: True
